In [19]:
import numpy as np
h1D=np.array([1,2,3])   
print("1st Array: ")
print(h1D)
print(f"Number of Dimention: {h1D.ndim}")   ##Number of dimention
print(f"Array Shape: {h1D.shape}")  ### array shape
print(f"item size: {h1D.itemsize}")
print(f"Size: {h1D.size}")
print(f"Number of bytes: {h1D.nbytes}")
print(f"Data type: {h1D.dtype}\n\n")


h2D=np.array([[1,2,3],[4,5,6]])  ### if want call data type ([1,2,3],[4,5,6],dtype="int64")
print("2nd array: ")
print(h2D)
print(f"Number of dimention: {h2D.ndim}")
print(f"Shape: {h2D.shape}")
print(f"item size: {h2D.itemsize}")
print(f"size: {h2D.size}")
print(f"Number of bytes: {h2D.nbytes}")
print(f"Data type: {h2D.dtype} \n\n")

1st Array: 
[1 2 3]
Number of Dimention: 1
Array Shape: (3,)
item size: 4
Size: 3
Number of bytes: 12
Data type: int32


2nd array: 
[[1 2 3]
 [4 5 6]]
Number of dimention: 2
Shape: (2, 3)
item size: 4
size: 6
Number of bytes: 24
Data type: int32 




In [48]:
# Accessing /changing specific elemants,rows,columns etc


a=np.array([[1,2,3,9,8,7],[4,5,6,3,2,1]])
print(a)
print(f"specific elemants 2nd row 3rd, column 6: {a[1,2]}")
print(f"specific elemants 1st row last, column 7: {a[0,-1]}")
print(f"Second row: {a[1,:]}")
print(f"first row: {a[0,:]}")
print("3rd column:",a[:,2])
print("5th column: ",a[:,4],"\n\n")


## getting little more fancy [startindex:endindex:stepsize]
print(a[1,0:-1:2])
print(a[0,1:-1:3],'\n\n')


### changing elemants
a[1,-1]=9
print(a)
a[0,-3]=6
print(a)
a[1,0]=8
print(a)
a[0,4]=4
print(a)

a[:,4]=[3,7]
print(a, "\n\n")


####3D array

b=np.array([[[1,2],[3,4]],[[5,6],[9,3]]])
print(b,'\n\n')
print("first row in 2nd row, 2nd colum -- 4: ",b[0,1,1])
print(f"secnd row in 1st row , 1st column---5: {b[1,0,0]} \n\n")

print(b[:,1,:],'\n\n')
print(b[:,0,:],'\n\n')

[[1 2 3 9 8 7]
 [4 5 6 3 2 1]]
specific elemants 2nd row 3rd, column 6: 6
specific elemants 1st row last, column 7: 7
Second row: [4 5 6 3 2 1]
first row: [1 2 3 9 8 7]
3rd column: [3 6]
5th column:  [8 2] 


[4 6 2]
[2 8] 


[[1 2 3 9 8 7]
 [4 5 6 3 2 9]]
[[1 2 3 6 8 7]
 [4 5 6 3 2 9]]
[[1 2 3 6 8 7]
 [8 5 6 3 2 9]]
[[1 2 3 6 4 7]
 [8 5 6 3 2 9]]
[[1 2 3 6 3 7]
 [8 5 6 3 7 9]] 


[[[1 2]
  [3 4]]

 [[5 6]
  [9 3]]] 


first row in 2nd row, 2nd colum -- 4:  4
secnd row in 1st row , 1st column---5: 5 


[[3 4]
 [9 3]] 


[[1 2]
 [5 6]] 


