In [2]:
import numpy as np
h1D=np.array([1,2,3])   
print("1st Array: ")
print(h1D)
print(f"Number of Dimention: {h1D.ndim}")   ##Number of dimention
print(f"Array Shape: {h1D.shape}")  ### array shape
print(f"item size: {h1D.itemsize}")
print(f"Size: {h1D.size}")
print(f"Number of bytes: {h1D.nbytes}")
print(f"Data type: {h1D.dtype}\n\n")


h2D=np.array([[1,2,3],[4,5,6]])  ### if want call data type ([1,2,3],[4,5,6],dtype="int64")
print("2nd array: ")
print(h2D)
print(f"Number of dimention: {h2D.ndim}")
print(f"Shape: {h2D.shape}")
print(f"item size: {h2D.itemsize}")
print(f"size: {h2D.size}")
print(f"Number of bytes: {h2D.nbytes}")
print(f"Data type: {h2D.dtype} \n\n")

1st Array: 
[1 2 3]
Number of Dimention: 1
Array Shape: (3,)
item size: 4
Size: 3
Number of bytes: 12
Data type: int32


2nd array: 
[[1 2 3]
 [4 5 6]]
Number of dimention: 2
Shape: (2, 3)
item size: 4
size: 6
Number of bytes: 24
Data type: int32 




In [49]:
# Accessing /changing specific elemants,rows,columns etc


a=np.array([[1,2,3,9,8,7],[4,5,6,3,2,1]])
print(a)
print(f"specific elemants 2nd row 3rd, column 6: {a[1,2]}")
print(f"specific elemants 1st row last, column 7: {a[0,-1]}")
print(f"Second row: {a[1,:]}")
print(f"first row: {a[0,:]}")
print("3rd column:",a[:,2])
print("5th column: ",a[:,4],"\n\n")


## getting little more fancy [startindex:endindex:stepsize]
print(a[1,0:-1:2])
print(a[0,1:-1:3],'\n\n')


### changing elemants
a[1,-1]=9
print(a)
a[0,-3]=6
print(a)
a[1,0]=8
print(a)
a[0,4]=4
print(a)

a[:,4]=[3,7]
print(a, "\n\n")


####3D array

b=np.array([[[1,2],[3,4]],[[5,6],[9,3]]])
print(b,'\n\n')
print("first row in 2nd row, 2nd colum -- 4: ",b[0,1,1])
print(f"secnd row in 1st row , 1st column---5: {b[1,0,0]} \n\n")

print(b[:,1,:],'\n\n')
print(b[:,0,:],'\n\n')
b[0,1,0]=7
print(b)

[[1 2 3 9 8 7]
 [4 5 6 3 2 1]]
specific elemants 2nd row 3rd, column 6: 6
specific elemants 1st row last, column 7: 7
Second row: [4 5 6 3 2 1]
first row: [1 2 3 9 8 7]
3rd column: [3 6]
5th column:  [8 2] 


[4 6 2]
[2 8] 


[[1 2 3 9 8 7]
 [4 5 6 3 2 9]]
[[1 2 3 6 8 7]
 [4 5 6 3 2 9]]
[[1 2 3 6 8 7]
 [8 5 6 3 2 9]]
[[1 2 3 6 4 7]
 [8 5 6 3 2 9]]
[[1 2 3 6 3 7]
 [8 5 6 3 7 9]] 


[[[1 2]
  [3 4]]

 [[5 6]
  [9 3]]] 


first row in 2nd row, 2nd colum -- 4:  4
secnd row in 1st row , 1st column---5: 5 


[[3 4]
 [9 3]] 


[[1 2]
 [5 6]] 


[[[1 2]
  [7 4]]

 [[5 6]
  [9 3]]]


In [60]:
###initializing different types of arrays

h=np.zeros(5)
print(h,'\n\n')
m=np.zeros((2,3))
print(m,'\n\n')
m=np.zeros((2,3,4))
print(m,'\n\n')
m=np.zeros((2,3,4,2),dtype="int32")
print(m,'\n\n')

m=np.ones((2,3,4),dtype="int32")
print(m,'\n\n')

m=np.full((2,3),47)
print(m)

[0. 0. 0. 0. 0.] 


[[0. 0. 0.]
 [0. 0. 0.]] 


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]] 


[[[[0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]]]


 [[[0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]]]] 


[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] 


[[47 47 47]
 [47 47 47]]


In [69]:
m=np.full_like(m,10)
print(m,'\n\n')
m=np.full(m.shape,7)
print(m)

m=np.random.rand(4,4)
print(m)

m=np.random.randint(2,7,size=(3,3))
print(m)

[[10 10 10]
 [10 10 10]
 [10 10 10]] 


[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.4981551  0.57437938 0.91775151 0.10941186]
 [0.48501827 0.50738101 0.44414776 0.85204236]
 [0.4856148  0.03118808 0.40538152 0.39108932]
 [0.89093264 0.30302338 0.76975769 0.43881442]]
[[5 2 3]
 [5 2 2]
 [5 6 2]]


In [70]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
arr=np.array([[1,2,3]])
r=np.repeat(arr,3,axis=0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [80]:
a=np.array([1,2,3])
# b=a
# b[2]=9
# print("this is a: ",a)
b=a.copy()
print("this is b: ",b)
b[1]=5
print("this is b: ",b)
print("This is a: ",a)

this is b:  [1 2 3]
this is b:  [1 5 3]
This is a:  [1 2 3]


In [23]:
#https://numpy.org/doc/stable/reference/routines.linalg.html ###there is lots of linear algebra equation function

a=np.array([[1,2,3],[4,5,6]])
h=np.array([[3,4,5],[7,9,3],[4,8,9]])
print(np.matmul(a,h))
print(np.min(h))
print(np.max(h))
print(np.max(h,axis=1))
print(np.sum(h, axis=0))

[[ 29  46  38]
 [ 71 109  89]]
3
9
[5 9 9]
[14 21 17]


In [13]:
h=np.array([[13,3,23],[30,7,53],[39,9,70]])   ####determent 
print(f"{np.linalg.det(h):.2f}")

1.00


In [29]:
### reorganizing arrays

before=np.array([[1,2,3,4],[5,8,3,2]])
print(before,'\n\n')

after=before.reshape((4,2))
print(after,'\n\n')

after3D=before.reshape((2,2,2))
print(after3D)

[[1 2 3 4]
 [5 8 3 2]] 


[[1 2]
 [3 4]
 [5 8]
 [3 2]] 


[[[1 2]
  [3 4]]

 [[5 8]
  [3 2]]]


In [32]:
## vertically stacking matrix
a=np.array([1,2,3])
b=np.array([5,6,3])
print(np.vstack([a,b]),'\n\n')
print(np.vstack([a,b,b,a,a]))

[[1 2 3]
 [5 6 3]] 


[[1 2 3]
 [5 6 3]
 [5 6 3]
 [1 2 3]
 [1 2 3]]


In [36]:
### horizontally staking matrix

a=np.array([1,2,3])
b=np.array([5,6,3])
           
print(np.hstack((a,b)))

[1 2 3 5 6 3]
